/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: ed2941c15b05e44a063213a256359092)
interface __BaseEnv_Env {
	ORIGIN_BASE_URL: "http://35.204.155.165:3000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./edge/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORIGIN_BASE_URL">> {}
}
