// Generated by scripts/provision-signing-key.mjs. Public keys are safe to publish.
// Every value is a base64-encoded Ed25519 SubjectPublicKeyInfo DER document.
export const trustedEd25519PublicKeys: readonly string[] = [
  "MCowBQYDK2VwAyEAWQRlXdCuUtwlMhG6JlXP+JhwKR80Dqp3lW36P22NXiM=",
];
